# Generated by Django 6.0.2 on 2026-10-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Project Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug / URL Identifier')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('category', models.CharField(choices=[('Interior Design', 'Interior Design'), ('Architecture', 'Architecture'), ('Turnkey Execution', 'Turnkey Execution')], max_length=100, verbose_name='Category')),
                ('property_type', models.CharField(choices=[('Private Villa', 'Private Villa'), ('Private Residence', 'Private Residence'), ('Penthouse Residence', 'Penthouse Residence'), ('Country Villa', 'Country Villa'), ('Heritage Residence', 'Heritage Residence'), ('Private Estate', 'Private Estate'), ('Boutique Commercial', 'Boutique Commercial'), ('Other', 'Other')], default='Private Villa', max_length=100, verbose_name='Property Type')),
                ('year', models.CharField(default='2025', max_length=50, verbose_name='Year Completed')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Built-Up Area')),
                ('short_description', models.CharField(max_length=350, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Full Description / Narrative')),
                ('design_approach', models.TextField(blank=True, verbose_name='Design Approach / Concept')),
                ('cover_image', models.CharField(max_length=500, verbose_name='Cover Image Path or URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, verbose_name='Image Path or URL')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption / Alt Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
