# Generated by Django 6.0.2 on 2026-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug / URL Key')),
                ('category', models.CharField(choices=[('Living Objects', 'Living Objects'), ('Architectural Lighting', 'Architectural Lighting'), ('Seating Collection', 'Seating Collection'), ('Tables & Consoles', 'Tables & Consoles'), ('Textiles & Accents', 'Textiles & Accents'), ('Other', 'Other')], max_length=100, verbose_name='Category')),
                ('price', models.CharField(max_length=100, verbose_name='Display Price (INR)')),
                ('numeric_price', models.PositiveIntegerField(default=0, verbose_name='Numeric Price (₹)')),
                ('image', models.CharField(max_length=500, verbose_name='Image Path or URL')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Image Alt Text')),
                ('dimensions', models.CharField(blank=True, max_length=200, verbose_name='Dimensions')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Material')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured on Homepage')),
                ('available', models.BooleanField(default=True, verbose_name='Available for Acquisition')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-featured', 'id'],
            },
        ),
    ]
