# Generated by Django 6.0.2 on 2026-10-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone / WhatsApp')),
                ('project_type', models.CharField(choices=[('Interior Design', 'Interior Design'), ('Architecture', 'Architecture'), ('Turnkey Execution', 'Turnkey Execution'), ('Other', 'Other')], max_length=100, verbose_name='Project Type')),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Office', 'Office'), ('Shop', 'Shop'), ('Other', 'Other')], max_length=100, verbose_name='Property Type')),
                ('project_location', models.CharField(max_length=255, verbose_name='Project Location')),
                ('project_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Approximate Area (sq.ft)')),
                ('budget_range', models.CharField(blank=True, choices=[('Below ₹5 Lakhs', 'Below ₹5 Lakhs'), ('₹5–10 Lakhs', '₹5–10 Lakhs'), ('₹10–25 Lakhs', '₹10–25 Lakhs'), ('₹25–50 Lakhs', '₹25–50 Lakhs'), ('₹50 Lakhs+', '₹50 Lakhs+')], max_length=100, null=True, verbose_name='Budget Range')),
                ('requirements', models.TextField(verbose_name='Project Requirements')),
                ('reference_images', models.FileField(blank=True, null=True, upload_to='enquiries/reference_images/', verbose_name='Reference Images')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In Discussion', 'In Discussion'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='New', max_length=50, verbose_name='Enquiry Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'Project Enquiry',
                'verbose_name_plural': 'Project Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
